---
- name: Ansible ACI Demo of gathering facts using a managed object  query
  hosts:  APIC-NGDC-East-1
  connection: local
  gather_facts: no

  vars:
    dn: comp/prov-VMware/ctrlr-[NGDC-VC]-VC_Cont

  tasks:
  - name: Managed Object (mo)  query for a VMware Vcenter managed object
    aci_gather_facts:
     URI: "/api/mo/{{dn}}.json"
     host: "{{hostname}}"
     username: admin
     password: "{{password}}"

  # This managed object query returns one element, however, because the MO variable
  # contains special characters in the name, e.g. / [  (see dn variable) we cannot reference
  # the variable directly, however we can reference it using a with_dict
  # it will only return one element.

  - name: debug  vCenter object variable vendor
    debug: var=item.value.vendor
    with_dict: compCtrlr

  - name: debug vCenter object variable model
    debug: var=item.value.model
    with_dict: compCtrlr

  - name: debug vCenter object by class (all fields)
    debug: var=compCtrlr

