---
#
#   Copyright (c) 2015 World Wide Technology, Inc.
#   All rights reserved.
#
#   author: Joel W. King, World Wide Technology
#
- name: Ansible ACI Demo of gathering facts using a class query
  hosts: prod-01
  connection: local
  gather_facts: no
  vars:
   IPaddr: 198.51.100.4

  tasks:
  - name: Find the MAC address given an IP address
    aci_gather_facts:
     queryfilter: 'eq(fvCEp.ip, "{{IPaddr}}")'
     URI: /api/class/fvCEp.json
     host: "{{hostname}}"
     username: admin
     password: "{{password}}"

  - name: Print fields, IP, mac, etc. 
    debug: msg=" ManagementIP {{ fvCEp[0].ip }}  mac {{ fvCEp[0].mac }} encap {{ fvCEp[0].encap }} "


